name: 'Build'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to be used in workflow.'
        required: true
        type: string

permissions:
  contents: read

jobs:
#  lint:
#    name: 'Lint'
#    runs-on: ubuntu-latest
#    container:
#      image: ${{ inputs.image }}
#      options: --user 1001
#    steps:
#      - name: 'Checkout'
#        uses: actions/checkout@v5
#      - name: 'Install'
#        uses: ./.github/actions/install
#      - name: 'Lint'
#        run: npm run lint
  fallbacks:
    name: 'Fallbacks'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v5
        with:
          name: build-fallbacks
          path: ./dist/
