name: 'Build'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to be used in workflow.'
        required: true
        type: string

permissions:
  contents: read

jobs:
#  lint:
#    name: 'Lint'
#    runs-on: ubuntu-latest
#    container:
#      image: ${{ inputs.image }}
#      options: --user 1001
#    steps:
#      - name: 'Checkout'
#        uses: actions/checkout@v6
#      - name: 'Install'
#        uses: ./.github/actions/install
#      - name: 'Lint'
#        run: npm run lint
  assets:
    name: 'Assets'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build --workspace=@porsche-design-system/assets
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v5
        with:
          name: build-fallbacks
          path: ./assets/dist/
  partials:
    name: 'Partials'
    needs:
      - assets
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download artifact'
        uses: actions/download-artifact@v6
        with:
          name: build-fallbacks
          path: ./assets/dist
      - name: 'Build'
        run: npm run build --workspace=@porsche-design-system/partials
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v5
        with:
          name: build-partials
          path: |
            ./partials/dist/
            ./partials/src/lib/
