name: 'Test'

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image to be used in workflow.'
        required: true
        type: string

permissions:
  contents: read

jobs:
  unit-assets:
    name: 'Unit (Assets)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Unit'
        run: npm run test:unit --workspace=@porsche-design-system/assets
        shell: bash
  vrt-assets:
   name: 'VRT (Assets)'
   runs-on: ubuntu-latest
   container:
     image: ${{ inputs.image }}
     options: --user 1001
   steps:
     - name: 'Checkout'
       uses: actions/checkout@v5
     - name: 'Install'
       uses: ./.github/actions/install
     - name: 'Download artifact'
       uses: actions/download-artifact@v6
       with:
         name: build-fallbacks
         path: ./assets/dist
     - name: 'VRT'
       run: npm run test:vrt --workspace=@porsche-design-system/assets
       shell: bash
     - name: 'VRT Regression'
       if: failure()
       uses: actions/upload-artifact@v5
       with:
         name: regression-vrt-fallbacks
         path: ./assets/tests/vrt/test-results
  unit-partials:
    name: 'Unit (Partials)'
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user 1001
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Download artifact'
        uses: actions/download-artifact@v6
        with:
          name: build-partials
          path: ./partials
      - name: 'Unit'
        run: npm run test:unit --workspace=@porsche-design-system/partials
        shell: bash
